name: Build and Release Executables

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller gitpython python-gitlab

    - name: Build executable
      run: |
        pyinstaller --onefile scripts/main.py

    - name: Set Artifact Name
      id: set_artifact_name
      run: echo "artifact_name=${{ matrix.os }}-generate-directory-tree-${{ github.ref }}" | sed 's/refs\/tags\///g' >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact_name }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Set Artifact Name
      id: set_artifact_name
      run: echo "artifact_name=${{ matrix.os }}-generate-directory-tree-${{ github.ref }}" | sed 's/refs\/tags\///g' >> $GITHUB_ENV

    - name: Download Ubuntu Artifact
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-generate-directory-tree-${{ env.artifact_name }}
        path: dist/ubuntu-latest

    - name: Upload Ubuntu Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/ubuntu-latest/main
        asset_name: generate-directory-tree-ubuntu-${{ env.artifact_name }}
        asset_content_type: application/octet-stream

    - name: Download MacOS Artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-latest-generate-directory-tree-${{ env.artifact_name }}
        path: dist/macos-latest

    - name: Upload MacOS Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/macos-latest/main
        asset_name: generate-directory-tree-macos-${{ env.artifact_name }}
        asset_content_type: application/octet-stream

    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-latest-generate-directory-tree-${{ env.artifact_name }}
        path: dist/windows-latest

    - name: Upload Windows Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/windows-latest/main.exe
        asset_name: generate-directory-tree-windows-${{ env.artifact_name }}
        asset_content_type: application/octet-stream
